site_name: Cashu NUTs Specifications
site_url: https://cashubtc.github.io/nuts/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  icon:
    logo: material/hand-coin
nav:
  - Home: README.md
  - NUTs:
      - Mandatory:
          - NUT-00: 00.md
          - NUT-01: 01.md
          - NUT-02: 02.md
          - NUT-03: 03.md
          - NUT-04: 04.md
          - NUT-05: 05.md
          - NUT-06: 06.md
          # Add more mandatory NUTs here
      - Optional:
          - NUT-07: 07.md
          - NUT-08: 08.md
          - NUT-09: 09.md
          - NUT-10: 10.md
          - NUT-11: 11.md
          - NUT-12: 12.md
          - NUT-13: 13.md
          - NUT-14: 14.md
          - NUT-15: 15.md
          - NUT-16: 16.md
          - NUT-17: 17.md
          # Add more optional NUTs here
plugins:
  - search
  - macros
  - section-index
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
