site_name: Cashu NUTs Specifications
site_url: https://cashubtc.github.io/nuts/
repo_url: https://github.com/cashubtc/nuts/
repo_name: cashubtc/nuts
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/hand-coin
    repo: fontawesome/brands/git-alt
nav:
  - Home: README.md
  - NUTs:
      - Mandatory:
          - NUT-00: 00.md
          - NUT-01: 01.md
          - NUT-02: 02.md
          - NUT-03: 03.md
          - NUT-04: 04.md
          - NUT-05: 05.md
          - NUT-06: 06.md
          # Add more mandatory NUTs here
      - Optional:
          - NUT-07: 07.md
          - NUT-08: 08.md
          - NUT-09: 09.md
          - NUT-10: 10.md
          - NUT-11: 11.md
          - NUT-12: 12.md
          - NUT-13: 13.md
          - NUT-14: 14.md
          - NUT-15: 15.md
          - NUT-16: 16.md
          - NUT-17: 17.md
          # Add more optional NUTs here
plugins:
  - search
  - macros
  - section-index
extra:
  social:
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/cashubtc
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
